[package]
name = "tapir-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tapirc"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
compiler = { path = "../compiler" }
